### ISSUE TITLE
Privacy Month Retweet Tip #18

### ISSUE THREAD

**Issue by vi5halc** [mozilla/reps-tweets#27] opened 2018-01-18 13:28 UTC
## Tweet should be about
Privacy Month Retweet Tip # 18 - Orfox

## Retweet
https://twitter.com/MozillaIN/status/953944413763334144

**Comment by MichaelKohler** [comment] 2018-01-18 13:52
Duplicate of #26

**Closed by MichaelKohler** 2018-01-18 13:52 UTC
Labels: Retweet, ready
